### PR TITLE
i18n: New Crowdin updates

### PR DESCRIPTION
**Pull request by razbakov**

### CODE REVIEW

**Review by best-lucky1030 — COMMENTED** [review]
rearranged for en.yml file?

**Comment by best-lucky1030** [comment]
resolved conflicts!

**Comment by razbakov** [comment]
@best-lucky1030 nice!

**Review by best-lucky1030 — COMMENTED** [review]
this PR is draft?

**Comment by razbakov** [comment]
@best-lucky1030 WeDance is working, you can see my commits in main branch coming every day and people posting events in the feed.

**Pull request merged**
