### PR TITLE
style: i18n

### PR DESCRIPTION
**Pull request by razbakov**
Shall we switch to this format of i18n files?

### CODE REVIEW

**Review by best-lucky1030 — COMMENTED** [review]
Looks good style 💯

**Comment by razbakov** [comment]
@best-lucky1030 you join meeting today?

**Comment by amanuela97** [comment]
This style has a clearer structure so I would say yes, unless making the switch causes issues that would outweigh the benefits

**Comment by Stefanacef** [comment]
I like this style, I think is more clear and we can avoid repetitions

**Pull request merged**
